write:
  name: headspace1
  parent_dir: /Users/jak/Documents/repos/fifteen.pm/public/assets/11/objects/
sources:
  - name: "Scan3D_20200304185937_repaired"
    parent_dir: "./data/jwords/"
    transforms:
      move:
        x: 4
    #   modifiers:
    #   - remesh:
    #       octree_depth: 5
    #       scale: .5
        decimate:
          ratio: 0.2

  - name: "Scan3D_20200304190659_repaired"
    parent_dir: "./data/jwords/"
    transforms:
      move:
        x: -5
    #   modifiers:
    #   - remesh:
    #       octree_depth: 5
    #       scale: .5
        decimate:
          ratio: 0.2

  # - name: "Scan3D_20200304195813_repaired"
    # parent_dir: "./data/jwords"
    # transforms:
    #   modifiers:
    #   - remesh:
    #       octree_depth: 5
    #       scale: .5
        # decimate:
          # ratio: 0.2

  # - name: "Scan3D_20200304203312_original"
    # parent_dir: "./data/jwords"
    # transforms:
    #   modifiers:
    #   - remesh:
    #       octree_depth: 5
    #       scale: .5
        # decimate:
        #   ratio: 0.2

  # - name: "Scan3D_20200304203703_repaired"
  #   parent_dir: "./data/jwords"
  #   transforms:
  #     modifiers:
    #     - remesh:
    #         octree_depth: 5
    #         scale: .5
    #       decimate:
    #         ratio: 0.2

  # - name: "Scan3D_20200304204307_original"
  #   parent_dir: "./data/jwords"
  #   transforms:
  #     modifiers:
    #     - remesh:
    #         octree_depth: 5
    #         scale: .5
    #       decimate:
    #         ratio: 0.2

  # - name: "Scan3D_20200304190426_repaired"
  #   parent_dir: "./data/jwords"
  #   transforms:
  #     modifiers:
    #     - remesh:
    #         octree_depth: 5
    #         scale: .5
    #       decimate:
    #         ratio: 0.2

  # - name: "Scan3D_20200304191652_repaired"
  #   parent_dir: "./data/jwords"
  #   transforms:
  #     modifiers:
    #     - remesh:
    #         octree_depth: 5
    #         scale: .5
    #       decimate:
    #         ratio: 0.2

  # - name: "Scan3D_20200304200658_original"
  #   parent_dir: "./data/jwords"
  #   transforms:
  #     modifiers:
    #     - remesh:
    #         octree_depth: 5
    #         scale: .5
    #       decimate:
    #         ratio: 0.2

  # - name: "Scan3D_20200304203312_repaired"
  #   parent_dir: "./data/jwords"
  #   transforms:
  #     modifiers:
    #     - remesh:
    #         octree_depth: 5
    #         scale: .5
    #       decimate:
    #         ratio: 0.2

  # - name: "Scan3D_20200304204207_original"
  #   parent_dir: "./data/jwords"
  #   transforms:
  #     modifiers:
    #     - remesh:
    #         octree_depth: 5
    #         scale: .5
    #       decimate:
    #         ratio: 0.2

  # - name: "Scan3D_20200304204307_repaired"
  #   parent_dir: "./data/jwords"
  #   transforms:
  #     modifiers:
    #     - remesh:
    #         octree_depth: 5
    #         scale: .5
    #       decimate:
    #         ratio: 0.2

  # - name: "Scan3D_20200304190659_original"
  #   parent_dir: "./data/jwords"
  #   transforms:
  #     modifiers:
    #     - remesh:
    #         octree_depth: 5
    #         scale: .5
    #       decimate:
    #         ratio: 0.2

  # - name: "Scan3D_20200304195813"
  #   parent_dir: "./data/jwords"
  #   transforms:
  #     modifiers:
    #     - remesh:
    #         octree_depth: 5
    #         scale: .5
    #       decimate:
    #         ratio: 0.2

  # - name: "Scan3D_20200304200658_repaired"
  #   parent_dir: "./data/jwords"
  #   transforms:
  #     modifiers:
    #     - remesh:
    #         octree_depth: 5
    #         scale: .5
    #       decimate:
    #         ratio: 0.2

  # - name: "Scan3D_20200304203703_original"
  #   parent_dir: "./data/jwords"
  #   transforms:
  #     modifiers:
    #     - remesh:
    #         octree_depth: 5
    #         scale: .5
    #       decimate:
    #         ratio: 0.2

  # - name: "Scan3D_20200304204207_repaired"
  #   parent_dir: "./data/jwords"
  #   transforms:
  #     modifiers:
    #     - remesh:
    #         octree_depth: 5
    #         scale: .5
    #       decimate:
    #         ratio: 0.2
